# TODO: 時間があったら軽量なalpineにしたい
# alpineにする際にはパッケージのインスコとかで色々変更が必要なので注意！
FROM ruby:2.5.3

# 必要なパッケージのインストール（基本的に必要になってくるものだと思うので削らないこと）
RUN apt-get update -qq && \
    apt-get install -y build-essential \ 
                       libpq-dev \        
                       nodejs           

# 作業ディレクトリの作成、設定
RUN mkdir /app
##作業ディレクトリ名をAPP_ROOTに割り当てて、以下$APP_ROOTで参照
ENV APP_ROOT /app
WORKDIR $APP_ROOT

# ホスト側（ローカル）のGemfileを追加する（ローカルのGemfileは【３】で作成）
ADD web/Gemfile $APP_ROOT/Gemfile
ADD web/Gemfile.lock $APP_ROOT/Gemfile.lock

# Gemfileのbundle install
RUN bundle install
# アプリケーション本体の配置
ADD web $APP_ROOT

# 本番環境は最後に実行が必要。docker-composeだとcompoes側で実行する。
CMD ["rails","server","-p","3000","-b","0.0.0.0"]
